{
 "title": "mysql slave 1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Slave IO Running status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slave Status Seconds Behing Master",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Slave Running Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}