apiVersion: v1
kind: Service
metadata:
  name: sretest-service
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: sretest
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sretest
  labels:
    app: sretest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sretest
  template:
    metadata:
      labels:
        app: sretest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/application
                operator: In
                values:
                - "sretest"
      containers:
      - name: sretest
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 3
            memory: 128Mi
          requests:
            cpu: 2
            memory: 128Mi

